proxies:
  - name: SG
    server: quiz.vidio.com
    port: 443
    type: vmess
    uuid: f03e9b29-bda4-4e36-81eb-a559d84c7857
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sgku.xensin.my.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: sgku.xensin.my.id
    udp: true
  - name: IDN
    server: quiz.vidio.com
    port: 80
    type: vmess
    uuid: b0cf9f90-664a-4111-b51b-71438460d6b5
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: my-indo.xensin.my.id
    network: ws
    ws-opts:
      path: /vmessws
      headers:
        Host: my-indo.xensin.my.id
    udp: true
  - name: Argon
    server: quiz.vidio.com
    port: 80
    type: vmess
    uuid: 49bd14fc-5676-4602-9531-a46671a8c4aa
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: argon-stb.bhm.my.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: argon-stb.bhm.my.id
    udp: true
  - name: zaki2
    server: my-indo.xensin.my.id
    port: 80
    type: vmess
    uuid: b0cf9f90-664a-4111-b51b-71438460d6b5
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: 172.67.5.14
    network: ws
    ws-opts:
      path: /vmessws
      headers:
        Host: 172.67.5.14
    udp: true
  - name: (kjGw4sKF) [VMess - ws] nonTLS ✅
    server: quiz.staging.vidio.com
    port: 80
    type: vmess
    uuid: 1eb5745f-bbfd-470f-b7f9-5898e822a5f4
    cipher: auto
    tls: false
    udp: true
    skip-cert-verify: true
    network: ws
    alterId: 0
    ws-opts:
      path: /vmess
      headers:
        Host: melbi2.server-vpn.cloud
