proxies:
  - name: SG
    server: quiz.vidio.com
    port: 80
    type: vmess
    uuid: f03e9b29-bda4-4e36-81eb-a559d84c7857
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: sgku.xensin.my.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: sgku.xensin.my.id
    udp: true
