proxies:
  - name: Qwords
    server: quiz.vidio.com
    port: 80
    type: vmess
    uuid: 9c0c1c49-b996-4b54-9168-d1551f08b15d
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: qwords.bhm.my.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: qwords.bhm.my.id
    udp: true
