proxies:
  - name: (zaki3) [Trojan - ws] TLS ✅
    server: quiz.int.vidio.com
    port: 8443
    type: trojan
    password: f08a273d-688f-4264-a0c9-f7bfb4aa6a41
    udp: true
    skip-cert-verify: true
    network: ws
    sni: argon-2.store-premium.online
    ws-opts:
      path: /trojan
      headers:
        Host: argon-2.store-premium.online
