proxies:
  - name: SG
    server: quiz.vidio.com
    port: 443
    type: vmess
    uuid: f03e9b29-bda4-4e36-81eb-a559d84c7857
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: true
    servername: sgku.xensin.my.id
    network: ws
    ws-opts:
      path: /vmess
      headers:
        Host: sgku.xensin.my.id
    udp: true
  - name: IDN
    server: quiz.vidio.com
    port: 80
    type: vmess
    uuid: b0cf9f90-664a-4111-b51b-71438460d6b5
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: my-indo.xensin.my.id
    network: ws
    ws-opts:
      path: /vmessws
      headers:
        Host: my-indo.xensin.my.id
    udp: true
  - name: zaki2
    server: my-indo.xensin.my.id
    port: 80
    type: vmess
    uuid: b0cf9f90-664a-4111-b51b-71438460d6b5
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: 172.67.5.14
    network: ws
    ws-opts:
      path: /vmessws
      headers:
        Host: 172.67.5.14
    udp: true
  - name: ZAKI3
    server: 104.22.5.240
    port: 443
    type: trojan
    password: df91cfa3-b6b5-47ba-9462-aaddaf1ca19a
    udp: true
    skip-cert-verify: true
    network: ws
    sni: warna2.store-premium.online
    ws-opts:
      path: /trojan
      headers:
        Host: warna2.store-premium.online
