proxies:
  - name: zaki2
    server: my-indo.xensin.my.id
    port: 80
    type: vmess
    uuid: b0cf9f90-664a-4111-b51b-71438460d6b5
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: 172.67.5.14
    network: ws
    ws-opts:
      path: /vmessws
      headers:
        Host: 172.67.5.14
    udp: true
