proxies:
  - name: (zaki3) [Trojan - ws] TLS ✅
    server: 104.22.5.240
    port: 443
    type: trojan
    password: dffb2628-fa51-47d7-b0d7-f2629fd13fe7
    udp: true
    skip-cert-verify: true
    network: ws
    sni: raja-mitra1.server-vpn.cloud
    ws-opts:
      path: /trojan
      headers:
        Host: raja-mitra1.server-vpn.cloud
